version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 2
  target-branch: develop
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: express-prom-bundle
    versions:
    - 6.3.0
    - 6.3.2
    - 6.3.3
    - 6.3.4
    - 6.3.5
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: "@types/bull"
    versions:
    - 3.15.0
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  rebase-strategy: disabled
