pull_request_rules:
  #######################
  # AUTO MERGING
  #######################
  - name: auto merge passing Dependabot pull requests
    conditions:
      # match dependabot[bot] and dependabot-preview[bot]
      - author~=dependabot(-preview)?\[bot\]
      - label~=dependencies
      - -status-neutral~=.*
      - -status-failure~=.*
    actions:
      merge:
        method: squash
        strict: true
  - name: auto merge when ready to merge label is set
    conditions:
      - label=ready to merge
    actions:
      merge:
        method: merge
        strict: true

  #######################
  # CLEANUP AFTER MERGE
  #######################
  - name: remove ready to merge when merged
    conditions:
      - merged
      - label=ready to merge
    actions:
      label:
        add:
          - mergified
        remove:
          - ready to merge
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}
