---
name: Build and push Docker image

on:
  push:
    branches-ignore:
      - main
      - master
      - dependabot/*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        redis-version: [5]
    steps:
     - name: Git checkout
       uses: actions/checkout@v1
     - name: Start Mailcatcher
       run: docker run --name mailcatcher --publish 1025:1025 --detach schickling/mailcatcher
     - name: Start MongoDB 
       uses: supercharge/mongodb-github-action@1.1.0
     - name: Start Redis
       uses: supercharge/redis-github-action@1.1.0
       with:
         redis-version: ${{ matrix.redis-version }}
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - run: npm install
     - run: npm run build
     - run: npm test
       env:
         CI: true
         
  build_and_push:
    needs: 
      - test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker meta Service Name
        id: docker_meta_img
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable=false,priority=600
            type=sha,enable=true,priority=600,prefix=
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_DOCKER_USERNAME }}
          password: ${{ secrets.GH_DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: ${{ steps.docker_meta_img.outputs.labels }}
          
  dispatch:
    runs-on: ubuntu-latest
    needs: 
      - build_and_push
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: hpi-schul-cloud/dof_app_deploy
          event-type: dev-deploy
          client-payload: '{"branch": "${{ steps.extract_branch.outputs.branch}}" }'