name: Build and push Docker image

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - hotfix/*
    paths-ignore:
      - '\.github/**'

  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make build
       
      - name: Log into registry
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push image
        run: make push
