name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        redis-version: [5]  # [4, 5]

    steps:
     - name: Git checkout
       uses: actions/checkout@v1
     - name: MongoDB 
       uses: supercharge/mongodb-github-action@1.1.0
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: Start Redis
       uses: supercharge/redis-github-action@1.1.0
       with:
         redis-version: ${{ matrix.redis-version }}
     - run: npm install
     - run: npm run build --if-present
     - run: npm test
       env:
         CI: true
